package com.example.shadow.heartrecreation.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.shadow.heartrecreation.db.db.DrinkDB;
import com.example.shadow.heartrecreation.db.db.MerchantDB;
import com.example.shadow.heartrecreation.db.db.OrderServeDB;
import com.example.shadow.heartrecreation.db.db.ServePersonnelDB;
import com.example.shadow.heartrecreation.db.db.UserDB;

import com.example.shadow.heartrecreation.db.DrinkDBDao;
import com.example.shadow.heartrecreation.db.MerchantDBDao;
import com.example.shadow.heartrecreation.db.OrderServeDBDao;
import com.example.shadow.heartrecreation.db.ServePersonnelDBDao;
import com.example.shadow.heartrecreation.db.UserDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig drinkDBDaoConfig;
    private final DaoConfig merchantDBDaoConfig;
    private final DaoConfig orderServeDBDaoConfig;
    private final DaoConfig servePersonnelDBDaoConfig;
    private final DaoConfig userDBDaoConfig;

    private final DrinkDBDao drinkDBDao;
    private final MerchantDBDao merchantDBDao;
    private final OrderServeDBDao orderServeDBDao;
    private final ServePersonnelDBDao servePersonnelDBDao;
    private final UserDBDao userDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        drinkDBDaoConfig = daoConfigMap.get(DrinkDBDao.class).clone();
        drinkDBDaoConfig.initIdentityScope(type);

        merchantDBDaoConfig = daoConfigMap.get(MerchantDBDao.class).clone();
        merchantDBDaoConfig.initIdentityScope(type);

        orderServeDBDaoConfig = daoConfigMap.get(OrderServeDBDao.class).clone();
        orderServeDBDaoConfig.initIdentityScope(type);

        servePersonnelDBDaoConfig = daoConfigMap.get(ServePersonnelDBDao.class).clone();
        servePersonnelDBDaoConfig.initIdentityScope(type);

        userDBDaoConfig = daoConfigMap.get(UserDBDao.class).clone();
        userDBDaoConfig.initIdentityScope(type);

        drinkDBDao = new DrinkDBDao(drinkDBDaoConfig, this);
        merchantDBDao = new MerchantDBDao(merchantDBDaoConfig, this);
        orderServeDBDao = new OrderServeDBDao(orderServeDBDaoConfig, this);
        servePersonnelDBDao = new ServePersonnelDBDao(servePersonnelDBDaoConfig, this);
        userDBDao = new UserDBDao(userDBDaoConfig, this);

        registerDao(DrinkDB.class, drinkDBDao);
        registerDao(MerchantDB.class, merchantDBDao);
        registerDao(OrderServeDB.class, orderServeDBDao);
        registerDao(ServePersonnelDB.class, servePersonnelDBDao);
        registerDao(UserDB.class, userDBDao);
    }
    
    public void clear() {
        drinkDBDaoConfig.clearIdentityScope();
        merchantDBDaoConfig.clearIdentityScope();
        orderServeDBDaoConfig.clearIdentityScope();
        servePersonnelDBDaoConfig.clearIdentityScope();
        userDBDaoConfig.clearIdentityScope();
    }

    public DrinkDBDao getDrinkDBDao() {
        return drinkDBDao;
    }

    public MerchantDBDao getMerchantDBDao() {
        return merchantDBDao;
    }

    public OrderServeDBDao getOrderServeDBDao() {
        return orderServeDBDao;
    }

    public ServePersonnelDBDao getServePersonnelDBDao() {
        return servePersonnelDBDao;
    }

    public UserDBDao getUserDBDao() {
        return userDBDao;
    }

}
