package com.example.shadow.heartrecreation.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.shadow.heartrecreation.db.db.MerchantDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MERCHANT_DB".
*/
public class MerchantDBDao extends AbstractDao<MerchantDB, Long> {

    public static final String TABLENAME = "MERCHANT_DB";

    /**
     * Properties of entity MerchantDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MerchantName = new Property(1, String.class, "MerchantName", false, "MERCHANT_NAME");
        public final static Property MerchantID = new Property(2, String.class, "MerchantID", false, "MERCHANT_ID");
        public final static Property MerchantImage = new Property(3, String.class, "MerchantImage", false, "MERCHANT_IMAGE");
        public final static Property BaofangType = new Property(4, String.class, "BaofangType", false, "BAOFANG_TYPE");
        public final static Property BaofangTypeID = new Property(5, String.class, "BaofangTypeID", false, "BAOFANG_TYPE_ID");
        public final static Property BaofangID = new Property(6, String.class, "BaofangID", false, "BAOFANG_ID");
        public final static Property BaofangName = new Property(7, String.class, "BaofangName", false, "BAOFANG_NAME");
        public final static Property Baofang = new Property(8, boolean.class, "Baofang", false, "BAOFANG");
        public final static Property BaofangNum = new Property(9, String.class, "BaofangNum", false, "BAOFANG_NUM");
        public final static Property BaofangMoney = new Property(10, String.class, "BaofangMoney", false, "BAOFANG_MONEY");
        public final static Property Lon = new Property(11, String.class, "lon", false, "LON");
        public final static Property Dem = new Property(12, String.class, "dem", false, "DEM");
        public final static Property MerchantAdds = new Property(13, String.class, "MerchantAdds", false, "MERCHANT_ADDS");
        public final static Property MerchatServicePrice = new Property(14, String.class, "MerchatServicePrice", false, "MERCHAT_SERVICE_PRICE");
    }


    public MerchantDBDao(DaoConfig config) {
        super(config);
    }
    
    public MerchantDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MERCHANT_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MERCHANT_NAME\" TEXT," + // 1: MerchantName
                "\"MERCHANT_ID\" TEXT," + // 2: MerchantID
                "\"MERCHANT_IMAGE\" TEXT," + // 3: MerchantImage
                "\"BAOFANG_TYPE\" TEXT," + // 4: BaofangType
                "\"BAOFANG_TYPE_ID\" TEXT," + // 5: BaofangTypeID
                "\"BAOFANG_ID\" TEXT," + // 6: BaofangID
                "\"BAOFANG_NAME\" TEXT," + // 7: BaofangName
                "\"BAOFANG\" INTEGER NOT NULL ," + // 8: Baofang
                "\"BAOFANG_NUM\" TEXT," + // 9: BaofangNum
                "\"BAOFANG_MONEY\" TEXT," + // 10: BaofangMoney
                "\"LON\" TEXT," + // 11: lon
                "\"DEM\" TEXT," + // 12: dem
                "\"MERCHANT_ADDS\" TEXT," + // 13: MerchantAdds
                "\"MERCHAT_SERVICE_PRICE\" TEXT);"); // 14: MerchatServicePrice
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MERCHANT_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MerchantDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String MerchantName = entity.getMerchantName();
        if (MerchantName != null) {
            stmt.bindString(2, MerchantName);
        }
 
        String MerchantID = entity.getMerchantID();
        if (MerchantID != null) {
            stmt.bindString(3, MerchantID);
        }
 
        String MerchantImage = entity.getMerchantImage();
        if (MerchantImage != null) {
            stmt.bindString(4, MerchantImage);
        }
 
        String BaofangType = entity.getBaofangType();
        if (BaofangType != null) {
            stmt.bindString(5, BaofangType);
        }
 
        String BaofangTypeID = entity.getBaofangTypeID();
        if (BaofangTypeID != null) {
            stmt.bindString(6, BaofangTypeID);
        }
 
        String BaofangID = entity.getBaofangID();
        if (BaofangID != null) {
            stmt.bindString(7, BaofangID);
        }
 
        String BaofangName = entity.getBaofangName();
        if (BaofangName != null) {
            stmt.bindString(8, BaofangName);
        }
        stmt.bindLong(9, entity.getBaofang() ? 1L: 0L);
 
        String BaofangNum = entity.getBaofangNum();
        if (BaofangNum != null) {
            stmt.bindString(10, BaofangNum);
        }
 
        String BaofangMoney = entity.getBaofangMoney();
        if (BaofangMoney != null) {
            stmt.bindString(11, BaofangMoney);
        }
 
        String lon = entity.getLon();
        if (lon != null) {
            stmt.bindString(12, lon);
        }
 
        String dem = entity.getDem();
        if (dem != null) {
            stmt.bindString(13, dem);
        }
 
        String MerchantAdds = entity.getMerchantAdds();
        if (MerchantAdds != null) {
            stmt.bindString(14, MerchantAdds);
        }
 
        String MerchatServicePrice = entity.getMerchatServicePrice();
        if (MerchatServicePrice != null) {
            stmt.bindString(15, MerchatServicePrice);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MerchantDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String MerchantName = entity.getMerchantName();
        if (MerchantName != null) {
            stmt.bindString(2, MerchantName);
        }
 
        String MerchantID = entity.getMerchantID();
        if (MerchantID != null) {
            stmt.bindString(3, MerchantID);
        }
 
        String MerchantImage = entity.getMerchantImage();
        if (MerchantImage != null) {
            stmt.bindString(4, MerchantImage);
        }
 
        String BaofangType = entity.getBaofangType();
        if (BaofangType != null) {
            stmt.bindString(5, BaofangType);
        }
 
        String BaofangTypeID = entity.getBaofangTypeID();
        if (BaofangTypeID != null) {
            stmt.bindString(6, BaofangTypeID);
        }
 
        String BaofangID = entity.getBaofangID();
        if (BaofangID != null) {
            stmt.bindString(7, BaofangID);
        }
 
        String BaofangName = entity.getBaofangName();
        if (BaofangName != null) {
            stmt.bindString(8, BaofangName);
        }
        stmt.bindLong(9, entity.getBaofang() ? 1L: 0L);
 
        String BaofangNum = entity.getBaofangNum();
        if (BaofangNum != null) {
            stmt.bindString(10, BaofangNum);
        }
 
        String BaofangMoney = entity.getBaofangMoney();
        if (BaofangMoney != null) {
            stmt.bindString(11, BaofangMoney);
        }
 
        String lon = entity.getLon();
        if (lon != null) {
            stmt.bindString(12, lon);
        }
 
        String dem = entity.getDem();
        if (dem != null) {
            stmt.bindString(13, dem);
        }
 
        String MerchantAdds = entity.getMerchantAdds();
        if (MerchantAdds != null) {
            stmt.bindString(14, MerchantAdds);
        }
 
        String MerchatServicePrice = entity.getMerchatServicePrice();
        if (MerchatServicePrice != null) {
            stmt.bindString(15, MerchatServicePrice);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MerchantDB readEntity(Cursor cursor, int offset) {
        MerchantDB entity = new MerchantDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // MerchantName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // MerchantID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // MerchantImage
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // BaofangType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // BaofangTypeID
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // BaofangID
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // BaofangName
            cursor.getShort(offset + 8) != 0, // Baofang
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // BaofangNum
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // BaofangMoney
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // lon
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // dem
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // MerchantAdds
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // MerchatServicePrice
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MerchantDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMerchantName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMerchantID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMerchantImage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBaofangType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBaofangTypeID(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBaofangID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBaofangName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBaofang(cursor.getShort(offset + 8) != 0);
        entity.setBaofangNum(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBaofangMoney(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLon(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDem(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMerchantAdds(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setMerchatServicePrice(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MerchantDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MerchantDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MerchantDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
